export const ADD_TO_CART = "ADD_TO_CART";
export const CHANGE_MESSAGE = "CHANGE_MESSAGE";
export const CHANGE_DELETE_CART_BUTTON = "CHANGE_DELETE_CART_BUTTON";
export const ON_UPDATE_QUANTITY = "ON_UPDATE_QUANTITY";
